### ISSUE TITLE
Road to v1 (beta)

### ISSUE THREAD

**Issue by danburzo** [Evercoder/culori#81]
Pretty happy with the API, but before I can confidently call it a `v1.0.0` there are some things to sort out:

* [x] Interpolation is too stuffy (#80)
* [x] Figure out alpha premultiplication (#79)
* [x] A minimal documentation site (#82)

Stretch goals (not essential):

* [ ] `average()` function (#78)
* [ ] non-separable blend modes, to support CSS blend modes completely (#75)

Other things to consider:

* [ ] gather more feedback on the current API 
* [ ] increase code coverage of tests
